logger:
  level: debug
  output: stdout  # "stdout" or "file"
  path: logs/seq.log  # Required when output is "file"
  max_byte_size: 10485760  # 10 MB in bytes (0 = no rotation)
  max_backup_files: 5  # Maximum number of backup files to keep (0 = keep all)

catalog:
  base_url: https://capi.lynxlinkage.com
  api_token: api_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwidXNlcm5hbWUiOiJlZGR5IiwiZW1haWwiOiJlZGR5QGx5bnhsaW5rYWdlLmNvbSIsImlzX2FjdGl2ZSI6dHJ1ZSwidHlwZSI6ImFwaV9hY2Nlc3MiLCJleHAiOjIwODQwMDUzNjgsImlhdCI6MTc2ODY0NTM2OC4wMTUyMDksImp0aSI6IktRZ1hpcmVlcndnIn0.EymHZoI887NV54z2apx9EZOFpf1OqJeUQSIBkXbVu_w

ems:
  url: http://localhost:8080
pms:
  url: http://localhost:8081
  database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: seq
    sslmode: disable  # disable, allow, prefer, require, verify-ca, verify-full