trading_mode: paper

logger:
  level: debug
  stdout: true
  file:
    dir: ./logs
    name: sma
    max_bytes: 10485760
    daily: true
    max_backups: 5
    max_age_days: 0
    sync: rotate

msgbus:
  msglog:
    enabled: true
    file:
      dir: ./logs/sma
      name: msg
      max_bytes: 104857600
      daily: true
      max_backups: 10
      max_age_days: 7
      sync: rotate

catalog:
  instruments: ./instruments.json

datarouter:
  - symbol: BINANCE_SPOT_ETHUSDT
    kline:
      interval: 1m

node:
  engine:
    data:
      actor: []

    execution:
      actor: []

    ledger:
      actor: []

    risk:
      actor: []

    strategy:
      actor:
        - type: sma
          name: sma-eth
          config:
            universal_ticker: BINANCE_SPOT_ETHUSDT
            interval: 1m
            period: 20
