logger:
  level: info
  output: file  # "stdout" or "file"
  path: /root/seq/logs/xarb-uni-usdt.log  # Required when output is "file"
  max_byte_size: 10485760  # 10 MB in bytes (0 = no rotation)
  max_backup_files: 5  # Maximum number of backup files to keep (0 = keep all)

msgbus:
  msglog:
    enabled: true
    dir: ./logs/

catalog:
  base_url: https://capi.lynxlinkage.com
  api_token: api_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwidHlwZSI6ImFwaV9hY2Nlc3MiLCJleHAiOjIwODY0MDU4MTcsImlhdCI6MTc3MTA0NTgxNy45NDI2NTgsImp0aSI6IndzUTJmQnFwaXc0In0.0Tm3yo-rcNmhOvwl3UB2Mc_WMxejDROOaRIXLDQKSxw

node:
  engine:
    data:
      subscriptions:
        - symbol: BINANCE_SPOT_UNIUSDT
          depth:
            type: delta
            push_rate: 100ms
        - symbol: BYBIT_SPOT_UNIUSDT
          depth:
            levels: 50
      actor:
        - type: orderbook
          name: orderbook-binance
          config:
            symbol: BINANCE_SPOT_UNIUSDT
        - type: orderbook
          name: orderbook-bybit
          config:
            symbol: BYBIT_SPOT_UNIUSDT

    execution:
      actor:
        - type: oms
          name: oms-bybit
          config:
            id: 6
            account: bybit-eddy
            wallet: bybit-hephe-unified
            api: bybit-eddy-hmac
        - type: oms
          name: oms-binance
          config:
            id: 5
            account: bn-eddy
            wallet: bn-eddy-spot
            api: bn-eddy-ed25519

    portfolio:
      actor:
        - type: balance
          name: balance-bybit
          config:
            id: 6
            account: bybit-eddy
            wallet: bybit-hephe-unified
            api: bybit-eddy-hmac
        - type: balance
          name: balance-binance
          config:
            id: 5
            account: bn-eddy
            wallet: bn-eddy-spot
            api: bn-eddy-ed25519

    strategy:
      actor:
        - type: xarb
          name: xarb-uni-buy-3bps
          config:
            quoting_symbol_universal_ticker: BINANCE_SPOT_UNIUSDT
            hedging_symbol_universal_ticker: BYBIT_SPOT_UNIUSDT
            quoting_account: bn-eddy
            hedging_account: bybit-eddy
            side: BUY
            profit_bps: 3
            qty: 3.5
            min_unhedged_quote: 10
        - type: xarb
          name: xarb-uni-sell-3bps
          config:
            quoting_symbol_universal_ticker: BINANCE_SPOT_UNIUSDT
            hedging_symbol_universal_ticker: BYBIT_SPOT_UNIUSDT
            quoting_account: bn-eddy
            hedging_account: bybit-eddy
            side: SELL
            profit_bps: 3
            qty: 3.5
            min_unhedged_quote: 10
